### ISSUE TITLE
setting model doesn't work

### ISSUE THREAD

**Issue by deepfates** [replicate/create-replicate-app#21]
Tried with various models including `yorickvp/llava-13b` as in the README but it always says `Model: stability-ai/sdxl...` 

First guess is maybe this string manip? Didn't try to pull this repo and develop on it yet.
https://github.com/replicate/create-replicate/blob/34d57dd2c7779e285e72a2ed9bd2562e4f56b331/lib/models.js#L15C4-L16C1

**Comment by zeke** [comment]
Ruh-roh. You might have a cached older version of the package?

~~Try this:~~

```
npm create replicate@latest --yorickvp/llava-13b
```

EDIT, I meant this:

```
npm create replicate@latest --model=yorickvp/llava-13b
```

**Comment by deepfates** [comment]
Just pulled `1.5.0` and it did the same thing :\

**Comment by deepfates** [comment]
NB i tried this with `--model=yorickvp/llava-13b` as well as the command you gave above which i believe is a typo? This is the output i get
```
$ npm create replicate@latest --model=yorickvp/llava-13b
Creating project "my-replicate-app"...
Model: stability-ai/sdxl...
Copying files...
API token not found in environment.
Open your browser to copy a Replicate API token? (Y/n) 
Paste your API token here: ****************************************
API token 68147 written to .env file
Invalid API token: [REDACTED]
Setting package name...
Installing dependencies...
Fetching model metadata using Replicate API...
Adding model data and inputs to index.js...
App created successfully!
Running command: `node my-replicate-app/index.js`
{
  model: 'stability-ai/sdxl:39ed52f2a78e934b3ba6e2a89f5b1c712de7dfea535525255b1aa35c5565e08b',
  input: {
    width: 768,
    height: 768,
    prompt: 'An astronaut riding a rainbow unicorn, cinematic, dramatic',
    refine: 'expert_ensemble_refiner',
    scheduler: 'K_EULER',
    lora_scale: 0.6,
    num_outputs: 1,
    guidance_scale: 7.5,
    apply_watermark: false,
    high_noise_frac: 0.8,
    negative_prompt: '',
    prompt_strength: 0.8,
    num_inference_steps: 25
  }
}
Running...

```

Also of note is it says my API token is invalid and prints it out? Redacted above. Not sure why it would do that because the API key does work

**Comment by zeke** [comment]
Okay I think I know what's happening here.

Two things:

- The Replicate API call is quietly failing and the script is falling back to the default model, SDXL
- The API token you're using is an old one, from before we introduced the `r8_` prefix, and my crude token validation doesn't work for old tokens.

I'll open fixes for both of these.

**Comment by zeke** [comment]
What's the length of that old token you're using?

> API token 68147 written to .env file

**Comment by deepfates** [comment]
> What's the length of that old token you're using?
> 
> > API token 68147 written to .env file

It is an old one, you're right. it's 41 characters, same as the new ones i have (including the prefix)

**Comment by zeke** [comment]
40 or 41? Should be 40 I think.

**Comment by zeke** [comment]
Oh weird I'm seeing that issue too now on the latest npm release but not on the main branch. 🤔 

What do you see when you run it locally?

```
git clone https://github.com/replicate/create-replicate
cd create-replicate
npm install
node index.mjs --model=yorickvp/llava-13b
```

**Comment by zeke** [comment]
I just cut a new release 1.6.0 but still seeing this behavior in the published package:

```
$ npm create replicate@latest --model=yorickvp/llava-13b
Need to install the following packages:
create-replicate@1.6.0
Ok to proceed? (y) y
Creating project "my-replicate-app"...
Model: stability-ai/sdxl...
```

It has something to do with the way `npm create` works (or doesn't work). Notice that when I globally install and invoke the installed package it works fine:

```
$ npm i -g create-replicate && create-replicate --model=yorickvp/llava-13b
Creating project "my-replicate-app"...
Model: yorickvp/llava-13b...
```

Also works fine with `npx`:

```
$ npx create-replicate@latest --model=yorickvp/llava-13b
Creating project "my-replicate-app"...
Model: yorickvp/llava-13b...
```

**Comment by zeke** [comment]
Figured it out: https://github.com/replicate/create-replicate/pull/30

Sheesh.
